### ISSUE TITLE
Question about syntax extending

### ISSUE THREAD

**Issue by OEvgeny** [stylecow/stylecow-core#3]
Stylecow has a powerful parser, it is well organized and has a great cli tool. As I can understand the main idea of Stylecow is fixing CSS, not extending its syntax. For the other hand it has extensions and practically it can do it. I mean CSS that was written with Stylecow in some cases will not work without precompilation.

I think it is *totaly* ok, but wonder why can't we go the way like LESS and SASS? Why can't we add some syntax extensions for Stylecow?

It would be very hard to implement without JavaScript. JS has some very cool features like eval and ability to dynamically create functions. Since Stylecow is written in JS we can use them and bring ability to run some js directly in style definition. We can organize scopes and evaluate peaces of js in current scope context.

It can be backward completable with current tasks. Implemented special rules and declarations can be accessible via new API methods. 

Why is this needed? - Look at this example:
```js
.foo {
    background-color:: Color(bgColor).lighten(25%).fade(12%).rgba();
    display:: flex ? 'flex' : 'block';
}
```

Note: It's just a simple example, I have no ideas about good syntax right now.

What are your thoughts on this?

**Comment by oscarotero** [comment]
The problem with syntax extending is you're creating a strong dependency with the processor. Things like that are possible with, for example, postcss that contains multiple plugins to extend the css language with many features.

Let's say for example [postcss-write-svg](https://github.com/jonathantneal/postcss-write-svg). It's great to write svg inside css, but because this never is going to become a standard (or yes, you never know), you will need this plugin always to compile the css. If the plugin is deprecated, unmaintained or whatever, all your css deppending of this plugin will also be deprecated and you will need to rewrite it to use other plugin (if exists) with it's own syntax or convert to plain css and svg. And having multiple plugins doing things like this is event worse.

The stylecow goal is to be more independent. The css you are creating now will be available in a future, even without processors (when all browsers supports variables, colors, etc), or if you want to change to, for example, cssnext (a postcss plugin with similar purpose than stylecow), your code will work fine, because the code used is standard.

That being said, what you're proposing is to insert javascript inside css. That is something that is covered in [css extensions](https://drafts.csswg.org/css-extensions/) (or will be covered in a future, it's a very early draft) and it would be great to have only if the javascript was executed in client side (the browser), so each element matching with the same selector can get different results, depending of the context. I thought about this but because css extensions are in a very early phase and there's no propossed syntax yet for custom functions, at-rules, etc, I preffer to wait instead create a syntax that will surely become deprecated in a future.

A way to play with this in stylecow is creating a plugin (using the standard syntax), for example:
```css
.foo {
    background: eval('return this.parentNode.styles.backgroundColor');
}
```
But this plugin won't be included in stylecow by default, because as said before, is not a standard. But can be installed and used independently.

**Comment by OEvgeny** [comment]
@oscarotero thanks for detailed response. You point is good enough to close this :) 
Syntax can be totally optional. But you are right, Stylecow solves another problems.

Just looking for a good API to do what I want. PostCSS is not good to do this imo. Stylecow is much better!

**Comment by oscarotero** [comment]
Great! Any suggestion or contribution will be appreciated :)
